# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - uses: sinoru/actions-setup-xcode@v1.1
      with:
        xcode-version: '11.4' # Exact version of a Xcode version to use
        apple-id: 'ci-appleid@damajash.org' # Apple ID to download from Apple Developer when Xcode not available in local
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
    - run: |
        source setup/setup_ios.sh
        npx cordova build ios
